version: 1.0

services:
  email-service:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_ADDRESS=${FROM_ADDR}
    restart: unless-stopped